from __future__ import annotations
from datetime import datetime
from sqlalchemy import DateTime, Float, ForeignKey, Integer, JSON, String, Text, UniqueConstraint, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

class Base(DeclarativeBase): pass
class User(Base):
    __tablename__="users"; id: Mapped[int]=mapped_column(Integer,primary_key=True); email: Mapped[str]=mapped_column(String(320),unique=True,index=True); password_hash: Mapped[str]=mapped_column(String(255)); is_active: Mapped[bool]=mapped_column(default=True); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); conversations: Mapped[list["Conversation"]]=relationship(back_populates="user",cascade="all, delete-orphan")
class Conversation(Base):
    __tablename__="conversations"; id: Mapped[str]=mapped_column(String(36),primary_key=True); user_id: Mapped[int]=mapped_column(ForeignKey("users.id"),index=True); title: Mapped[str]=mapped_column(String(200),default="New conversation"); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); updated_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now()); user: Mapped[User]=relationship(back_populates="conversations"); messages: Mapped[list["Message"]]=relationship(back_populates="conversation",cascade="all, delete-orphan",order_by="Message.created_at")
class Message(Base):
    __tablename__="messages"; id: Mapped[str]=mapped_column(String(36),primary_key=True); conversation_id: Mapped[str]=mapped_column(ForeignKey("conversations.id"),index=True); role: Mapped[str]=mapped_column(String(20)); content: Mapped[str]=mapped_column(Text); metadata_json: Mapped[dict]=mapped_column("metadata",JSON,default=dict); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); conversation: Mapped[Conversation]=relationship(back_populates="messages")
class Memory(Base):
    __tablename__="memories"; id: Mapped[str]=mapped_column(String(36),primary_key=True); user_id: Mapped[int]=mapped_column(ForeignKey("users.id"),index=True); content: Mapped[str]=mapped_column(Text); kind: Mapped[str]=mapped_column(String(32),default="fact"); importance: Mapped[float]=mapped_column(Float,default=.5); embedding: Mapped[list]=mapped_column(JSON); metadata_json: Mapped[dict]=mapped_column("metadata",JSON,default=dict); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); last_accessed_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class Document(Base):
    __tablename__="documents"; id: Mapped[str]=mapped_column(String(36),primary_key=True); user_id: Mapped[int | None]=mapped_column(ForeignKey("users.id"),nullable=True,index=True); source: Mapped[str]=mapped_column(String(1024)); title: Mapped[str]=mapped_column(String(512)); content: Mapped[str]=mapped_column(Text); embedding: Mapped[list]=mapped_column(JSON); metadata_json: Mapped[dict]=mapped_column("metadata",JSON,default=dict); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class APIKey(Base):
    __tablename__="api_keys"; __table_args__=(UniqueConstraint("key_prefix"),); id: Mapped[str]=mapped_column(String(36),primary_key=True); user_id: Mapped[int]=mapped_column(ForeignKey("users.id"),index=True); key_prefix: Mapped[str]=mapped_column(String(16)); key_hash: Mapped[str]=mapped_column(String(255)); name: Mapped[str]=mapped_column(String(80)); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); revoked_at: Mapped[datetime | None]=mapped_column(DateTime(timezone=True),nullable=True)
class DatasetAsset(Base):
    __tablename__="dataset_assets"; id: Mapped[str]=mapped_column(String(36),primary_key=True); user_id: Mapped[int]=mapped_column(ForeignKey("users.id"),index=True); name: Mapped[str]=mapped_column(String(200)); path: Mapped[str]=mapped_column(String(2048),unique=True); format: Mapped[str]=mapped_column(String(32),default="jsonl"); task: Mapped[str]=mapped_column(String(32),default="sft"); records: Mapped[int]=mapped_column(Integer,default=0); size_bytes: Mapped[int]=mapped_column(Integer,default=0); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class TrainingRun(Base):
    __tablename__="training_runs"; id: Mapped[str]=mapped_column(String(36),primary_key=True); user_id: Mapped[int]=mapped_column(ForeignKey("users.id"),index=True); name: Mapped[str]=mapped_column(String(120)); task: Mapped[str]=mapped_column(String(32)); status: Mapped[str]=mapped_column(String(24),default="queued",index=True); dataset_id: Mapped[str]=mapped_column(ForeignKey("dataset_assets.id")); config_json: Mapped[dict]=mapped_column("config",JSON,default=dict); metrics_json: Mapped[dict]=mapped_column("metrics",JSON,default=dict); output_dir: Mapped[str]=mapped_column(String(2048)); log_path: Mapped[str]=mapped_column(String(2048)); process_id: Mapped[int | None]=mapped_column(Integer,nullable=True); return_code: Mapped[int | None]=mapped_column(Integer,nullable=True); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); started_at: Mapped[datetime | None]=mapped_column(DateTime(timezone=True),nullable=True); finished_at: Mapped[datetime | None]=mapped_column(DateTime(timezone=True),nullable=True)
